// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcRRYPMyM7xrrxw16PVS_jTLUQDDaCll4',
    appId: '1:319618916859:web:ae68a726a513ef30da2b5e',
    messagingSenderId: '319618916859',
    projectId: 'test-delete-53051',
    authDomain: 'test-delete-53051.firebaseapp.com',
    storageBucket: 'test-delete-53051.appspot.com',
    measurementId: 'G-C0E2D5ZG47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxZd2io4Bw5EO3JpilO1WOJU4ZI_9PyX0',
    appId: '1:319618916859:android:f25d247396bb2b6eda2b5e',
    messagingSenderId: '319618916859',
    projectId: 'test-delete-53051',
    storageBucket: 'test-delete-53051.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJx2Zx5CCZNRG5VX0nhRgPLkhhR9imkVI',
    appId: '1:319618916859:ios:fe5fe387e9aa942eda2b5e',
    messagingSenderId: '319618916859',
    projectId: 'test-delete-53051',
    storageBucket: 'test-delete-53051.appspot.com',
    iosBundleId: 'com.example.testDelete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJx2Zx5CCZNRG5VX0nhRgPLkhhR9imkVI',
    appId: '1:319618916859:ios:fe5fe387e9aa942eda2b5e',
    messagingSenderId: '319618916859',
    projectId: 'test-delete-53051',
    storageBucket: 'test-delete-53051.appspot.com',
    iosBundleId: 'com.example.testDelete',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcRRYPMyM7xrrxw16PVS_jTLUQDDaCll4',
    appId: '1:319618916859:web:0a90a5c0f4390660da2b5e',
    messagingSenderId: '319618916859',
    projectId: 'test-delete-53051',
    authDomain: 'test-delete-53051.firebaseapp.com',
    storageBucket: 'test-delete-53051.appspot.com',
    measurementId: 'G-S6JJ537VGR',
  );
}
